import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar/index.tsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CatalogoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      <div className="flex">
        <Sidebar />
        {children}
      </div>
    </div>
  );
}
