"use client";
import { useXToast } from "@/components/XToast";
import { useEffect } from "react";

import "./globals.css";
import { XToastContextProvider } from "@/contexts/XToastContext";
// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    const handleLoginShortcut = async (event: KeyboardEvent) => {
      if (
        event.ctrlKey &&
        event.altKey &&
        event.shiftKey &&
        event.key === "L"
      ) {
        const loginWindow = window.open(
          "/admin/login",
          "_blank",
          "height=400,width=500"
        )!;
        loginWindow.focus();
        window.location.reload();

        const onLoadLoginWindow = () => {
          const larguraTela =
            window.innerWidth ||
            document.documentElement.clientWidth ||
            document.body.clientWidth;
          const alturaTela =
            window.innerHeight ||
            document.documentElement.clientHeight ||
            document.body.clientHeight;

          const larguraJanela =
            loginWindow.innerWidth ||
            loginWindow.document.documentElement.clientWidth ||
            loginWindow.document.body.clientWidth;
          const alturaJanela =
            loginWindow.innerHeight ||
            loginWindow.document.documentElement.clientHeight ||
            loginWindow.document.body.clientHeight;

          const left = Math.max(0, (larguraTela - larguraJanela) / 2);
          const top = Math.max(0, (alturaTela - alturaJanela) / 2);

          loginWindow.moveTo(left, top);
        };
        loginWindow.onload = onLoadLoginWindow;
      }
    };

    document.addEventListener("keydown", handleLoginShortcut);

    return () => {
      document.removeEventListener("keydown", handleLoginShortcut);
    };
  }, []);
  return (
    <html lang="en">
      <body className="h-screen bg-zinc-50">
        <XToastContextProvider>{children}</XToastContextProvider>
      </body>
    </html>
  );
}
